### ISSUE TITLE
Environment setup failed in example ppo_discrete.py

### ISSUE THREAD

**Issue by neil-tan** [philtabor/ProtoRL#6]
I have some trouble running `protorl/examples/ppo_discrete.py` The output is attached below.

```bash
python ppo_discrete.py 
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
Process Process-3:
Traceback (most recent call last):
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 11, in worker
    env = env_fn_wrapper.x()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 122, in _thunk
    env = gym.wrappers.AtariPreprocessing(env, noop_max=no_ops, scale_obs=True)
  File "/home/neil/.pyenv/versions/3.9.6/envs/ml_sandbox/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 88, in __init__
    raise ValueError(
ValueError: Disable frame-skipping in the original env. Otherwise, more than one frame-skip will happen as through this wrapper
Process Process-4:
Traceback (most recent call last):
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 11, in worker
    env = env_fn_wrapper.x()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 122, in _thunk
    env = gym.wrappers.AtariPreprocessing(env, noop_max=no_ops, scale_obs=True)
  File "/home/neil/.pyenv/versions/3.9.6/envs/ml_sandbox/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 88, in __init__
    raise ValueError(
ValueError: Disable frame-skipping in the original env. Otherwise, more than one frame-skip will happen as through this wrapper
Process Process-5:
Traceback (most recent call last):
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 11, in worker
    env = env_fn_wrapper.x()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 122, in _thunk
    env = gym.wrappers.AtariPreprocessing(env, noop_max=no_ops, scale_obs=True)
  File "/home/neil/.pyenv/versions/3.9.6/envs/ml_sandbox/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 88, in __init__
    raise ValueError(
ValueError: Disable frame-skipping in the original env. Otherwise, more than one frame-skip will happen as through this wrapper
Process Process-2:
Process Process-8:
Traceback (most recent call last):
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 11, in worker
    env = env_fn_wrapper.x()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 122, in _thunk
    env = gym.wrappers.AtariPreprocessing(env, noop_max=no_ops, scale_obs=True)
  File "/home/neil/.pyenv/versions/3.9.6/envs/ml_sandbox/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 88, in __init__
    raise ValueError(
ValueError: Disable frame-skipping in the original env. Otherwise, more than one frame-skip will happen as through this wrapper
Traceback (most recent call last):
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 11, in worker
    env = env_fn_wrapper.x()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 122, in _thunk
    env = gym.wrappers.AtariPreprocessing(env, noop_max=no_ops, scale_obs=True)
  File "/home/neil/.pyenv/versions/3.9.6/envs/ml_sandbox/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 88, in __init__
    raise ValueError(
ValueError: Disable frame-skipping in the original env. Otherwise, more than one frame-skip will happen as through this wrapper
Process Process-6:
Traceback (most recent call last):
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 11, in worker
    env = env_fn_wrapper.x()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 122, in _thunk
    env = gym.wrappers.AtariPreprocessing(env, noop_max=no_ops, scale_obs=True)
  File "/home/neil/.pyenv/versions/3.9.6/envs/ml_sandbox/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 88, in __init__
    raise ValueError(
ValueError: Disable frame-skipping in the original env. Otherwise, more than one frame-skip will happen as through this wrapper
Process Process-7:
Traceback (most recent call last):
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 11, in worker
    env = env_fn_wrapper.x()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 122, in _thunk
    env = gym.wrappers.AtariPreprocessing(env, noop_max=no_ops, scale_obs=True)
  File "/home/neil/.pyenv/versions/3.9.6/envs/ml_sandbox/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 88, in __init__
    raise ValueError(
ValueError: Disable frame-skipping in the original env. Otherwise, more than one frame-skip will happen as through this wrapper
Traceback (most recent call last):
  File "/home/neil/code/repos/ProtoRL/protorl/examples/ppo_discrete.py", line 64, in <module>
    main()
  File "/home/neil/code/repos/ProtoRL/protorl/examples/ppo_discrete.py", line 60, in main
    scores, steps_array = ep_loop.run(n_games)
  File "/home/neil/code/repos/ProtoRL/protorl/loops/ppo_episode.py", line 41, in run
    observation, info = self.env.reset()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 69, in reset
    remote.send(('reset', None))
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function SubprocVecEnv.__del__ at 0x7ff7ce170310>
Traceback (most recent call last):
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 100, in __del__
    self.close()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 91, in close
    self.close_extras()
  File "/home/neil/code/repos/ProtoRL/protorl/wrappers/vec_env.py", line 83, in close_extras
    remote.send(('close', None))
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/home/neil/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by philtabor** [comment]
Stupid mistake on my part. Thats' what I get for pushing code late at night. 

The issue was in the vec_env wrapper, in the make_vec_envs function. I got rid of passing in the name in the make_single_env function, but I was still passing "i" to the function in line 132 of make_vec_envs. This caused use_atari to evaluate to True.

Fixed in the most recent commit.
